version: "3"
services:
  train_lr:
    image: abajorat/lr_training:v1
    build: train/.
    volumes:
      - ./models/lr:/app/models
    command: python -m src.train_model LogisticRegression

  serve_lr:
    build: serve/.
    image: abajorat/serve_lr:v1
    depends_on:
      train_lr:
        condition: service_completed_successfully
    ports:
      - 8002:5002
    volumes:
      - ./models/lr:/app/models
      - ./logs/lr:/app/logs/
    command: uvicorn src.predict:app --host 0.0.0.0 --port 5002
