version: "3"
services:
  titanic_rf:
    build: predict/.
    image: abajorat/titanic_rf
    ports:
      - 8001:8000
    volumes:
      - ./models/rf:/app/models
      - ./logs/rf:/app/logs/
    command: uvicorn src.predict:app --host 0.0.0.0
  titanic_lr:
    build: predict/.
    image: abajorat/titanic_lr
    ports:
      - 8000:8000
    volumes:
      - ./models/lr:/app/models
      - ./logs/lr:/app/logs/
    command: uvicorn src.predict:app --host 0.0.0.0
