version: "3"
services:
  titanic_rf:
    build: predict/.
    image: abajorat/titanic_rf:staging
    ports:
      - 8001:8000
    volumes:
      - ./models/rf:/app/models
      - ./logs/rf:/app/logs/
  titanic_lr:
    build: predict/.
    image: abajorat/titanic_lr:staging
    ports:
      - 8000:8000
    volumes:
      - ./models/lr:/app/models
      - ./logs/lr:/app/logs/
