# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ staging, main]
  workflow_dispatch:

jobs:
  deploy-prod:
    name: Build
    runs-on: ubuntu-latest
    # if: ${{ github.ref_name == 'main' }}
    steps:
      - name: executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf titanic
            git clone git@github.com:abajorat93/titanic.git
            cd titanic
            sudo docker-compose build
            sudo docker-compose up -d
  deploy-staging:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ ${GITHUB_REF##*/} == 'staging' }}
    steps:
      - name: executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf titanic
            git clone git@github.com:abajorat93/titanic.git
            cd titanic
            sudo docker-compose build
            sudo docker-compose up -d